# Generated by Django 3.2 on 2021-04-29 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('shoe_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('brand', models.CharField(blank=True, max_length=80, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('length2', models.FloatField(blank=True, null=True)),
                ('width', models.CharField(blank=True, choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C (Narrow)'), ('D', 'D (Medium)'), ('E', 'E (Wide)'), ('EE', 'EE'), ('EEE', 'EEE'), ('?', 'Unknown')], max_length=10, null=True)),
                ('width2', models.CharField(blank=True, choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C (Narrow)'), ('D', 'D (Medium)'), ('E', 'E (Wide)'), ('EE', 'EE'), ('EEE', 'EEE'), ('?', 'Unknown')], max_length=10, null=True)),
                ('foot', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both'), ('?', 'Unknown')], max_length=10, null=True)),
                ('sex', models.CharField(blank=True, choices=[('N', 'Man'), ('W', 'Woman'), ('NA', 'N/A')], max_length=5, null=True)),
                ('purchaseURL', models.URLField(blank=True, max_length=2000, null=True)),
                ('imageURL', models.URLField(blank=True, max_length=2000, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shoe',
                'verbose_name_plural': 'Shoes',
            },
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('leftSize', models.FloatField(blank=True, null=True)),
                ('leftWidth', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C (Narrow)'), ('D', 'D (Medium)'), ('E', 'E (Wide)'), ('EE', 'EE'), ('EEE', 'EEE'), ('?', 'Unknown')], max_length=10)),
                ('rightSize', models.FloatField(blank=True, null=True)),
                ('rightWidth', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C (Narrow)'), ('D', 'D (Medium)'), ('E', 'E (Wide)'), ('EE', 'EE'), ('EEE', 'EEE'), ('?', 'Unknown')], max_length=10)),
                ('sex', models.CharField(blank=True, choices=[('N', 'Man'), ('W', 'Woman'), ('NA', 'N/A')], max_length=10, null=True)),
                ('authUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('phrase', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('width', models.CharField(blank=True, choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C (Narrow)'), ('D', 'D (Medium)'), ('E', 'E (Wide)'), ('EE', 'EE'), ('EEE', 'EEE'), ('?', 'Unknown')], max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('foot', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both'), ('?', 'Unknown')], max_length=10, null=True)),
                ('sex', models.CharField(blank=True, choices=[('N', 'Man'), ('W', 'Woman'), ('NA', 'N/A')], max_length=5, null=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.siteuser')),
            ],
        ),
    ]
